version: "3"
services:
  pfm:
    image: osallou/pfm:latest
    environment:
        MYSQL_HOST: mysql # Full URL to the mysql server
        MYSQL_DBNAME: platformmanager # name of the database on the mysql server
        MYSQL_USER: platform_manager # Admin account to connect to mysql
        MYSQL_PASS: ${MYSQL_PASSWORD} # Password to connect to mysql
        SMTP_HOST: mailhog
        SMTP_PORT: 1025
        MAIL_FROM: support@genouest.org
    depends_on:
        - mysql
        - mailhog
    volumes:
      - ./data:/var/www/platformmanager/data # Mount the application data directory
    ports:
      - "3000:80"

  mailhog:
    image: mailhog/mailhog
    ports:
        - "8025:8025"

  mysql:
    image: mysql:5.5
    environment:
        MYSQL_DATABASE: platformmanager
        MYSQL_USER: platform_manager
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
